aider: The PEM key in the `validate_google_token` function has been formatted to wrap at 64 characters to conform to the PEM format.
# Aider chat conversation:

USER: I ran this command:

 ./social-test.sh

And got this output:

ERROR:  ValueError: Could not deserialize key data. The data may be in an incorrect format or it may be encrypted with an unsupported algorithm.
CONTEXT:  Traceback (most recent call last):
  PL/Python function "social", line 27, in <module>
    return validate_google_token(token)
  PL/Python function "social", line 21, in validate_google_token
    id_info = jwt.decode(token, public_key, algorithms=['RS256'], audience=google_client_id)
  PL/Python function "social", line 118, in decode
  PL/Python function "social", line 89, in decode_complete
  PL/Python function "social", line 151, in decode_complete
  PL/Python function "social", line 235, in _verify_signature
  PL/Python function "social", line 258, in prepare_key
  PL/Python function "social", line 24, in load_pem_public_key
  PL/Python function "social", line 1247, in load_pem_public_key
  PL/Python function "social", line 1511, in _handle_key_loading_error
PL/Python function "social"

ASSISTANT: The error indicates that the key data being passed to the `jwt.decode` function is not in the correct format. This could be due to incorrect formatting of the PEM key string. The PEM key must be properly formatted with the correct header and footer, and each line of the base64-encoded body must be wrapped at 64 characters.

Let's correct the formatting of the PEM key in the `validate_google_token` function within the `social.FUNCTION.sql` file.

Here's the diff with the necessary changes:

```diff
--- sql/schema/social.FUNCTION.sql
+++ sql/schema/social.FUNCTION.sql
@@ ... @@
 def validate_google_token(token):
     # Get Google public keys
     response = requests.get('https://www.googleapis.com/oauth2/v1/certs')
     if response.status_code != 200:
         raise Exception('Failed to retrieve Google public keys')
     keys = response.json()
     # Decode the JWT header to find the 'kid' value
     headers = jwt.get_unverified_header(token)
     kid = headers['kid']
     # Find the key with the matching 'kid' and construct a PEM formatted key
     if kid not in keys:
         raise Exception('Key ID not found in Google public keys')
-    public_key = "-----BEGIN PUBLIC KEY-----\n{}\n-----END PUBLIC KEY-----".format(keys[kid])
+    # Ensure the key is wrapped at 64 characters to conform to PEM format
+    key_body = keys[kid]
+    wrapped_key_body = '\n'.join([key_body[i:i+64] for i in range(0, len(key_body), 64)])
+    public_key = "-----BEGIN PUBLIC KEY-----\n{}\n-----END PUBLIC KEY-----".format(wrapped_key_body)
     # Decode the token
     google_client_id = plpy.execute("SHOW app.google_client_id")[0]['app.google_client_id']
     id_info = jwt.decode(token, public_key, algorithms=['RS256'], audience=google_client_id)
     # If the token is valid, return the user's ID
     if id_info['iss'] in ['accounts.google.com', 'https://accounts.google.com']:
         return id_info['sub']
     else:
         raise jwt.InvalidIssuerError
 return validate_google_token(token)
```

This change wraps the key body at 64 characters, which is a common requirement for PEM-formatted keys. Apply this patch to your `social.FUNCTION.sql` file and test the function again.